# -*- coding: utf-8 -*-
"""파생상품_최종보고_코드_원지원

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xm-U-hhnOq4osMksS282gDedB6vD8zZk
"""

!pip install yfinance
!pip install arch

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import yfinance as yf
from arch import arch_model

issue_date = '2025-12-19'
maturity_date = '2028-12-18'

obs_dates = [
    '2026-03-17',
    '2026-06-16',
    '2026-09-15',
    '2026-12-15',
    '2027-03-16',
    '2027-06-15',
    '2027-09-14',
    '2027-12-14',
    '2028-03-14',
    '2028-06-13',
    '2028-09-15'
]

strike_price = np.array([0.90,0.90,0.90,0.90,0.90,0.90,0.85,0.85,0.85,0.80,0.80])
coupon = np.array([0.0266,0.0532,0.0798,0.1064,0.1330,0.1596,0.1862,0.2128,0.2394,0.2660,0.2926])

maturity_coupon = 0.3192
maturity_strike = 0.75
kib = 0.45

asset_name = ['Nikkei225','EUROSTOXX50','KOSPI200']

prd = []
for d in obs_dates:
    prd.append(np.busday_count(issue_date, d))
check_day = np.array(prd)

total_day = np.busday_count(issue_date, maturity_date)

tickers = {
    "Nikkei225": "^N225",
    "EUROSTOXX50": "^STOXX50E",
    "KOSPI200": "^KS200"
}

start = "2018-01-01"
end = None

data = pd.DataFrame()
for k,v in tickers.items():
    tmp = yf.download(v, start=start, end=end, auto_adjust=True, progress=False)["Close"]
    data[k] = tmp

data = data.dropna()
returns = data.pct_change().dropna()

corr_matrix = returns.corr()
vol = returns.std() * np.sqrt(252)

USE_GARCH = False

if USE_GARCH:
    garch_vol = {}
    for col in returns.columns:
        r_tmp = (returns[col] * 100).dropna()
        model = arch_model(r_tmp, vol='Garch', p=1, o=0, q=1, dist='Normal')
        results = model.fit(disp='off')
        annual_garch_vol = results.conditional_volatility.iloc[-1] * np.sqrt(252) / 100
        garch_vol[col] = float(annual_garch_vol)
    garch_vol = pd.Series(garch_vol)

oneyear = 252
dt = 1/oneyear
r = 0.03
q = np.array([0.0, 0.0, 0.0])

S0 = np.array([100.0, 100.0, 100.0])

if USE_GARCH:
    sigma = np.array([garch_vol['Nikkei225'], garch_vol['EUROSTOXX50'], garch_vol['KOSPI200']])
else:
    sigma = np.array([vol['Nikkei225'], vol['EUROSTOXX50'], vol['KOSPI200']])

corr_mat = corr_matrix.values
L = np.linalg.cholesky(corr_mat)

n = 20000
S = np.zeros((total_day+1, n, 3))
S[0,:,:] = S0

mu = (r - q)

for i in range(1, total_day+1):
    e0 = np.random.normal(0, 1, size=(n, 3))
    e = np.matmul(e0, L.T)
    S[i,:,:] = S[i-1,:,:] * np.exp((mu - 0.5*sigma**2)*dt + sigma*np.sqrt(dt)*e)

S_checkday = S[check_day,:,:]
R_check = S_checkday / S0
WP_check = np.minimum(np.minimum(R_check[:,:,0], R_check[:,:,1]), R_check[:,:,2])

R_all = S / S0
KI = (R_all < kib).any(axis=0).any(axis=1)

payoff = np.zeros(n)
case = np.array(['']*n, dtype=object)

for j in range(n):
    done = False
    for i in range(len(check_day)):
        if WP_check[i, j] >= strike_price[i]:
            payoff[j] = 1.0 + coupon[i]
            case[j] = f"autocall_{i+1}"
            done = True
            break

    if not done:
        WP_T = min(R_all[-1, j, 0], R_all[-1, j, 1], R_all[-1, j, 2])
        if WP_T >= maturity_strike:
            payoff[j] = 1.0 + maturity_coupon
            case[j] = "maturity_good"
        else:
            if (KI[j] == False):
                payoff[j] = 1.0 + maturity_coupon
                case[j] = "maturity_noKI"
            else:
                payoff[j] = WP_T
                case[j] = "maturity_KI_worst"

discount_payoff = payoff * np.exp(-r * (total_day/oneyear))

payoff_s = pd.Series(payoff)
p_loss = (payoff_s < 1.0).mean()
mean_return = (payoff_s - 1.0).mean()
q05 = payoff_s.quantile(0.05)
ES5 = payoff_s[payoff_s <= q05].mean()

plt.figure()
plt.hist(payoff, bins=80)
plt.title("Investor payoff distribution")
plt.show()

issuer_cashflow = payoff
issuer_tail = np.quantile(issuer_cashflow, 0.95)
issuer_low = np.quantile(issuer_cashflow, 0.05)

plt.figure()
plt.hist(issuer_cashflow, bins=80)
plt.title("Issuer cashflow distribution (no hedge)")
plt.show()

R_all = S / S0
W = np.minimum(np.minimum(R_all[:,:,0], R_all[:,:,1]), R_all[:,:,2])

hedge_steps = [1, 5, 21]
tc_list = [0.0005, 0.0010]

KI_weight = np.where(KI, 1.2, 1.0)

def issuer_proxy(W, hedge_step=5, tc=0.0005):
    idx = np.arange(0, W.shape[0], hedge_step)
    if idx[-1] != W.shape[0]-1:
        idx = np.append(idx, W.shape[0]-1)

    W_h = W[idx, :]
    dW = np.diff(W_h, axis=0)
    turnover = np.sum(np.abs(dW), axis=0)
    cost = tc * turnover
    qv = np.sum(dW**2, axis=0)
    hedge_error = qv * hedge_step
    risk_index = (cost + hedge_error) * KI_weight

    return risk_index

issuer_results = []
for hs in hedge_steps:
    for tc in tc_list:
        risk_index = issuer_proxy(W, hedge_step=hs, tc=tc)
        issuer_results.append({
            "hedge_step": hs,
            "tc": tc,
            "VaR5_risk": np.quantile(risk_index, 0.95),
            "ES5_risk": np.mean(risk_index[risk_index >= np.quantile(risk_index, 0.95)])
        })

issuer_table = pd.DataFrame(issuer_results)

plt.figure()
for tc in tc_list:
    tmp = issuer_table[issuer_table["tc"]==tc].sort_values("hedge_step")
    plt.plot(tmp["hedge_step"], tmp["VaR5_risk"], marker='o', label=f"tc={tc}")
plt.title("Issuer Proxy Tail Risk (95% quantile) vs hedge frequency")
plt.xlabel("hedge_step (days)")
plt.ylabel("VaR5_risk (bigger = worse)")
plt.legend()
plt.show()

def investor_payoff_from_S(S_input):
    """
    Calculates the investor's payoff based on the simulated asset prices.

    Args:
        S_input (np.ndarray): Simulated asset prices over time for n simulations.

    Returns:
        tuple: A tuple containing:
            - payoff (np.ndarray): Array of final payoffs for each simulation.
            - case (np.ndarray): Array indicating the payoff case for each simulation.
            - KI_local (np.ndarray): Array indicating if a Knock-In event occurred for each simulation.
    """
    # Recalculate R_check, WP_check, R_all, and KI based on the S_input
    R_check = S_input[check_day,:,:] / S0
    WP_check = np.minimum(np.minimum(R_check[:,:,0], R_check[:,:,1]), R_check[:,:,2])

    R_all_local = S_input / S0
    KI_local = (R_all_local < kib).any(axis=0).any(axis=1)

    payoff_local = np.zeros(n)
    case_local = np.array(['']*n, dtype=object)

    for j in range(n):
        done = False
        for i in range(len(check_day)):
            if WP_check[i, j] >= strike_price[i]:
                payoff_local[j] = 1.0 + coupon[i]
                case_local[j] = f"autocall_{i+1}"
                done = True
                break

        if not done:
            WP_T = min(R_all_local[-1, j, 0], R_all_local[-1, j, 1], R_all_local[-1, j, 2])
            if WP_T >= maturity_strike:
                payoff_local[j] = 1.0 + maturity_coupon
                case_local[j] = "maturity_good"
            else:
                if (KI_local[j] == False):
                    payoff_local[j] = 1.0 + maturity_coupon
                    case_local[j] = "maturity_noKI"
                else:
                    payoff_local[j] = WP_T
                    case_local[j] = "maturity_KI_worst"
    return payoff_local, case_local, KI_local

corr_stress_list = [0.6, 0.8, 0.9]

def simulate_S_with_corr(corr_level):
    corr_mat_s = np.ones((3,3)) * corr_level
    np.fill_diagonal(corr_mat_s, 1.0)
    L_s = np.linalg.cholesky(corr_mat_s)

    S_s = np.zeros((total_day+1, n, 3))
    S_s[0,:,:] = S0

    for i in range(1, total_day+1):
        e0 = np.random.normal(0, 1, size=(n, 3))
        e = np.matmul(e0, L_s.T)
        S_s[i,:,:] = S_s[i-1,:,:] * np.exp((mu - 0.5*sigma**2)*dt + sigma*np.sqrt(dt)*e)

    return S_s

stress_summary = []

for rho_s in corr_stress_list:
    S_s = simulate_S_with_corr(rho_s)

    R_all_s = S_s / S0
    W_s = np.minimum(np.minimum(R_all_s[:,:,0], R_all_s[:,:,1]), R_all_s[:,:,2])
    KI_s = (R_all_s < kib).any(axis=0).any(axis=1)

    payoff_s, _, KI_s = investor_payoff_from_S(S_s)

    p_loss_s = (payoff_s < 1.0).mean()
    mean_return_s = (payoff_s - 1.0).mean()
    q05_s = np.quantile(payoff_s, 0.05)
    ES5_s = payoff_s[payoff_s <= q05_s].mean()

    KI_weight = np.where(KI_s, 1.2, 1.0)

    for hs in hedge_steps:
        for tc in tc_list:
            risk_index = issuer_proxy(W_s, hedge_step=hs, tc=tc)
            stress_summary.append({
                "corr_level": rho_s,
                "hedge_step": hs,
                "tc": tc,
                "Investor_p_loss": p_loss_s,
                "Investor_mean_return": mean_return_s,
                "Investor_ES5_payoff": ES5_s,
                "Issuer_VaR5_risk": np.quantile(risk_index, 0.95),
                "Issuer_ES5_risk": np.mean(risk_index[risk_index >= np.quantile(risk_index, 0.95)])
            })

stress_table = pd.DataFrame(stress_summary)

plt.figure()
for hs in hedge_steps:
    tmp = stress_table[(stress_table["hedge_step"]==hs) & (stress_table["tc"]==tc_list[0])].sort_values("corr_level")
    plt.plot(tmp["corr_level"], tmp["Issuer_VaR5_risk"], marker='o', label=f"hedge_step={hs}")
plt.title("Issuer Proxy Tail Risk vs Crisis Correlation (tc fixed)")
plt.xlabel("corr_level (stress)")
plt.ylabel("Issuer_VaR5_risk (bigger = worse)")
plt.legend()
plt.show()

plt.figure()
tmp = stress_table[(stress_table["hedge_step"]==21) & (stress_table["tc"]==tc_list[0])].sort_values("corr_level")
plt.plot(tmp["corr_level"], tmp["Investor_p_loss"], marker='o', label="Investor p_loss")
plt.plot(tmp["corr_level"], tmp["Issuer_VaR5_risk"], marker='o', label="Issuer VaR5_risk")
plt.title("Investor vs Issuer under Crisis Correlation (monthly hedge)")
plt.xlabel("corr_level")
plt.legend()
plt.show()

pivot = stress_table.pivot_table(
    index=["corr_level","hedge_step","tc"],
    values=["Investor_p_loss","Investor_mean_return","Investor_ES5_payoff","Issuer_VaR5_risk","Issuer_ES5_risk"]
).reset_index()

pivot

import statsmodels.api as sm
df_test = stress_table[
    (stress_table["hedge_step"] == 21) &
    (stress_table["tc"] == 0.0005)
]

X = df_test["corr_level"]
X = sm.add_constant(X)
y = df_test["Issuer_VaR5_risk"]

model = sm.OLS(y, X).fit()
print(model.summary())